### ISSUE TITLE
Mehrsprachigkeit ist gewünscht

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-contact#17]
- gewünschte Sprachen in Settings einstellbar machen
- Übersetzte Felder von den APIs beziehen
- pro Sprache jeweils editierbare Felder ausgeben
- Sprach-Attribut in den Shortcodes

(Bedarf kam in der Webmaster-Sprechstunde 03.11.2022 auf)

**Comment by cassandre** [comment]
Die gewünschten Sprachen können aus dem Multilang-Plugin ausgelesen werden.

**Comment by thenickless** [comment]
Unter Verwendung von rrze-multilang:

```
public static function getLocaleInfo()
    {
        return class_exists('\RRZE\Multilang\Helper') ? \RRZE\Multilang\Helper::getLocaleInfo() : null;
    }
    
public static function getPostTranslations($postId)
    {
        return class_exists('\RRZE\Multilang\Helper') ? \RRZE\Multilang\Helper::getPostTranslations($postId) : null;
    }
```

Bsp:
shortcode checkt mit getPostTranslations($postId), ob Übersetzung vorhanden ist. Falls nicht, returned  getPostTranslations($postId) NULL, ansonsten das Post-Object der Übersetzung

**Comment by xwolfde** [comment]
obsolet, da es mit den FAUdir erstmal keine lokalen Daten geben wird und die übersetzten Daten aus FAUdir/ API kommen werden.
