### ISSUE TITLE
Bildgröße und Sprechstunden

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-contact#20]
(aus 🎫 http://go.fau.de/9t9ok | #18)

## Plugin-Einstellungen – Verständliche Bildgrößen
Für einen Kontakt X wurde kein Format spezifiziert, für einen weiteren Kontakt Y wurde das format="sidebar" definiert.

Beides, "kein Format" und "sidebar" sind weder "page", noch "card", sodass es laut Einstellungen die Thumbnail-Bildgröße sein müsste. Die Bilder sind aber verschieden groß und ändern sich - soweit ich das aufgrund des Anzeigen-Delays beurteilen kann - nicht wenn ich die Thumbnail-Größe ändere.

(Evtl. Zusammenhang mit dem Zwischenspeicher, da die Änderungen nicht mehr sofort sichtbar werden)

## Sprechstunden auf der Startseite
Die Überschrift der Sprechstunden auf der Startseite wird zu Groß dargestellt.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/58593037/214559838-70acb5a4-1c7a-4f6e-b60e-76e8b5d247b2.png">

## Komma hinter einem Sprechstunden-Eintrag?
Am Ende des Tages / Ortes wird immer ein Komma angezeigt. Frage war: Wie bekommt man das Komma weg?
<img width="369" alt="image" src="https://user-images.githubusercontent.com/58593037/214560126-28fb4d0c-8978-4c5a-b403-395df820f229.png">

**Comment by xwolfde** [comment]
durch neue CSS Techniken dann obsolet.
