### ISSUE TITLE
PublonLink wird im alten Plugin anscheinend nicht gespeichert / ausgegeben

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-contact#21]
Kunde meldet:

Wenn ich bei meinem Mitarbeiter XY [1]
zusaetzlich zu den vorhandenen Icons/Links (Twitter
bis Tiktok) auch eine URL zu seiner Publon-Seite eingebe [2],
ist die eingegebene URL nach dem Aktualisieren/Speichern
wieder verschwunden.

Auch im Wiederholungsfall verschwindet die eingegebene
URL beim Speicher.

Details und Beispiel s. 🎫 http://go.fau.de/9uimi

**Comment by xwolfde** [comment]
im neuen FAUdir Plugin werden alle SoMe-Plattformen ausgegeben . Dazu werden diese dann nochmal geprüft.
