### ISSUE TITLE
Bugs im rrze-person -> in rrze-contact auch prüfen

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-contact#22]
1) "Wenn man in einer englischen Seite den Kontakt auf
englisch einblendet, dann steht beim Büro: "Raum",
siehe Screenshot. Ich würde mir "Office" wünschen (oder
wenn es sein muss auch "Room")."
- [ ]  Translation & einstellbar machen

2) "Nicht hübsch ist folgendes: Wenn aus
Univis eine Telefon-Nummer importiert wird, dann
erscheint diese so, wie sie im Univis erfasst ist.
Bei Mobil-Telefonnummern werden hingegen die im
Univis vorhandenen Leerzeichen/Spaces aus der Nummer
getrimmt/entfernt. Aus der Univis-Mobilnummer
+49 174 608 3749 wird also im Plugin +491746083749.
Die Univis-Festnetznummer +49 9131 85-27621
wird hingegen 1:1 vom Plugin übernommen. Das ist
inkonsistent. Da die Nummern untereinander angezeigt
werden, ist es wenig hübsch - siehe Screenshot."
- [ ] formatUnivIS() mit dem vom Jobportal und rrze-univis vergleichen

https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=1076524

**Comment by xwolfde** [comment]
obsolet für neue Daten, da dies in FAUdir behandelt wird
