### ISSUE TITLE
Übersetzung für einzelne Begriffe (aus Helpdesk)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-contact#23]
Ergänzend zu #17 

Es gab den Wunsch:

Wenn man in einer englischen Seite den Kontakt auf englisch einblendet, dann steht beim Büro: "Raum",
siehe Screenshot. Ich würde mir "Office" wünschen (oder wenn es sein muss auch "Room").

Screenshot und Kundenmail s. Helpdesk: 🎫 http://go.fau.de/9uimi

**Comment by xwolfde** [comment]
Wird im neuen FAUdir Plugin generell hinsichtlich Übersetzungen geprüft.
