### ISSUE TITLE
Wunsch auf einheitliche Darstellung von Rufnummern (Aus Helpdesk)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-contact#24]
# Problem / Feature Request:

Nicht hübsch ist folgendes: Wenn aus Univis eine Telefon-Nummer importiert wird, dann erscheint diese so, wie sie im Univis erfasst ist.

Bei Mobil-Telefonnummern werden hingegen die im Univis vorhandenen Leerzeichen/Spaces aus der Nummer getrimmt/entfernt. Aus der Univis-Mobilnummer +49 174 608 1234 wird also im Plugin +491746081234.

Die Univis-Festnetznummer +49 9131 85-12345 wird hingegen 1:1 vom Plugin übernommen. Das ist inkonsistent. Da die Nummern untereinander angezeigt werden, ist es wenig hübsch - siehe Screenshot.

## Zusatzinformationen:
Screenshot und Kundenmail s. 🎫 http://go.fau.de/9uimi

**Comment by thenickless** [comment]
danke, hatte ich schon als Issue erfasst
