### ISSUE TITLE
Kein Code?

### ISSUE THREAD

**Issue by H6pOJTyp** [RRZE-Webteam/rrze-contact#31]
Liebes RRZE-Webteam,
ist das `rrze-contact` noch das Plugin-der-Wahl um an der FAU in Wordpress
Kontaktdaten anzuzeigen?  Falls ja, könntet Ihr bitte den aktuellen Code
ins Repo tun? Grade ist nur eine `LICENSE` drin.

Ein FAU-Plugin-User

**Comment by xwolfde** [comment]
Dieses Repo ist momentan nur ein Platzhalter für das neue noch zu entwickelnde Plugin, welches das alte FAU-Person (https://github.com/RRZE-Webteam/fau-person) ablösen soll .
"rrze-contact" gibt es so also noch garnicht ;)
