### ISSUE TITLE
Adressdaten: Digitale Erreichbarkeitsdaten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-contact#4]
Möglichkeiten zur Ergänzung der digitalen Erreichbarkeit ergänzen:

- Teams
- Zoom
- Andere Chatlösung

**Comment by thenickless** [comment]
2DO: entsprechende callbacks einbauen. 

Teams Link könnte über callto:email@domain.tld funktionieren. Falls unsere eMail Adr verwendet werden, dropdown mit bestehenden eMail Adr vom Kontakt, da beliebig viele Locations (daran hängt eMail) vorhanden sein können. Vielleicht aber besser Freitext-Feld, da es auch sein kann, dass eine eMail ausschließlich für Teams verwendet wird.
In jedem Fall: callback sanitize eMail

**Comment by xwolfde** [comment]
Nur Daten aus FAUdir. Da sind die obigen Daten dabei -  oder auch nicht.
