### ISSUE TITLE
Weitere Adresseinträge sollen auch angezeigt werden können

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-contact#6]
Manche UnivIS-Einträge haben einen zweiten oder sogar dritten Adresseintrag, zum Beispiel eine zweite Telefonnummer oder eine Postadresse. Es gibt momentan keine Möglichkeit, diese weiteren Adresseinträge auf fau.de anzeigen zu lassen.

**Comment by thenickless** [comment]
ist in rrze-contact 0.0.13 umgesetzt
