### ISSUE TITLE
Standort-Daten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-contact#9]
Strassennummer bitte von Strassennamen trennen um eine genauere Deklaration via Opengraph zu ermöglichen und ggf. auch eine bessere Suche für Kartendienste zu erlauben.
Optional auch Koordinaten eingeben und Gebäudenummer (FAMOS-ID) mit der man in karte.fau.de suchen könnte eingebbar machen.

Bei der Ausgabe mit fau_standort() ggf. auch die Möglichkeit einbauen, optional die FAU-Karte als embedding mit auszugeben.

**Comment by thenickless** [comment]
2DO: optionaler Link zur FAU-Karte

Siehe RRZE-Univis 

`            'MAP' => (!empty($term['room']['north']) && !empty($term['room']['east']) ? 'https://karte.fau.de/api/v1/iframe/marker/' . $term['room']['north'] . ',' . $term['room']['east'] . '/zoom/16' : ''),
`

**Comment by xwolfde** [comment]
obsolet für neues plugin, da Daten aus FAUdir
